name: Build Test

# on:
#   pull_request:
#     branches: [develop]

on: [push]

jobs:
  build:
    name: Build, lint, and test project
    timeout-minutes: 10
    runs-on: 'ubuntu-latest'

    env:
      CI_JOB_NUMBER: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies with yarn
        run: npm install

      - name: Build with yarn
        run: npm run build

      - name: Check size limits
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
